### ISSUE TITLE
better build documentation

### ISSUE THREAD

**Issue by tee3** [jwiegley/subconvert#2]
I having difficulty building subconvert, could you write up a quick procedure?

My guess is that this is not intended for others' use, which probably explains why it is difficult to build.  However, I would like to try subconvert on a large subversion repository that is not the Boost repository.

**Comment by jwiegley** [comment]
> > > > > tee3  reply@reply.github.com writes:
> 
> I having difficulty building subconvert, could you write up a quick
> procedure?

Sure thing, I'll try to get that into a README today.  Look for an update on
the GitHub project.

John

**Comment by tee3** [comment]
Thanks, that's great!  Once I get it built and running, I'll report back about my experience.  I'm trying to convert a multi-project Subversion repository into many smaller git repositories.  It is a bit like boost in that everything can be independent and it has a very complicated history.

**Comment by jwiegley** [comment]
Sorry it's taking me so much time to get to this documentation for you, tee.  Any chance you can find me on #ledger on irc.freenode.net, and we can discuss it in realtime so that I can document subconvert as I walk you through the process?

**Comment by tee3** [comment]
Sorry, I wasn't online this morning at that time.  I'm sure you are very busy and I appreciate the time you are taking to get me started.  I'm trying to build on Mac OS X Lion, but I will try it on Linux sometime today and see how that goes.  The default gcc is gcc 4.2.1 and I've tried gcc-4.7 as well, which gives less errors (-Weverything is unknown).

Maybe I can ask a few questions.
1. What operating system do you build it on?
2. What compiler and version do you build it with?
3. What arguments to configure do you use?
4. What version of boost is required?
5. Are there any other system requirements such as libraries, etc.?

I'm running the following commands.  

$ ./autogen.sh
$ ./configure --with-boost-suffix=-mt CPPFLAGS=-I/usr/local/include/boost LDFLAGS=-L/usr/local/lib
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define **EXTENSIONS**... yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking whether make sets $(MAKE)... (cached) yes
checking build system type... x86_64-apple-darwin11.3.0
checking host system type... x86_64-apple-darwin11.3.0
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/llvm-gcc-4.2/libexec/gcc/i686-apple-darwin11/4.2.1/ld
checking if the linker (/usr/llvm-gcc-4.2/libexec/gcc/i686-apple-darwin11/4.2.1/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm
checking the name lister (/usr/bin/nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-apple-darwin11.3.0 file names to x86_64-apple-darwin11.3.0 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin11.3.0 file names to toolchain format... func_convert_file_noop
checking for /usr/llvm-gcc-4.2/libexec/gcc/i686-apple-darwin11/4.2.1/ld option to reload object files... -r
checking for objdump... no
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/llvm-gcc-4.2/libexec/gcc/i686-apple-darwin11/4.2.1/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin11.3.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/llvm-gcc-4.2/libexec/gcc/i686-apple-darwin11/4.2.1/ld
checking if the linker (/usr/llvm-gcc-4.2/libexec/gcc/i686-apple-darwin11/4.2.1/ld) is GNU ld... no
checking whether the g++ linker (/usr/llvm-gcc-4.2/libexec/gcc/i686-apple-darwin11/4.2.1/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fno-common -DPIC
checking if g++ PIC flag -fno-common -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/llvm-gcc-4.2/libexec/gcc/i686-apple-darwin11/4.2.1/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin11.3.0 dyld
checking how to hardcode library paths into programs... immediate
checking if boost_filesystem is available... true
checking for ANSI C header files... (cached) yes
checking whether stat file-mode macros are broken... no
checking openssl/md5.h usability... yes
checking openssl/md5.h presence... yes
checking for openssl/md5.h... yes
checking openssl/sha.h usability... yes
checking openssl/sha.h presence... yes
checking for openssl/sha.h... yes
checking for MD5 in -lcrypto... yes
checking for SHA1 in -lcrypto... yes
checking for git_oid_fmt in -lgit2... no
checking for size_t... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
$ make
cp -p src/system.hpp.in system.hpp
make  all-am
  CXX    subconvert-svndump.o
cc1plus: error: unrecognized command line option "-Weverything"
cc1plus: error: unrecognized command line option "-Wno-weak-vtables"
cc1plus: error: unrecognized command line option "-Wno-exit-time-destructors"
cc1plus: error: unrecognized command line option "-Wno-disabled-macro-expansion"
cc1plus: error: unrecognized command line option "-Wno-header-hygiene"
make[1]: **\* [subconvert-svndump.o] Error 1
make: **\* [all] Error 2

**Comment by tee3** [comment]
I just found your scripts in the ./bin directory.  I guess you are using gcc-4.8 and clang-3.1.  I'm assuming this is the start of my issues, I'll try to get those versions installed and try again.

**Comment by jwiegley** [comment]
> > > > > tee3  reply@reply.github.com writes:
> 
> Sorry, I wasn't online this morning at that time.  I'm sure you are very
> busy and I appreciate the time you are taking to get me started.  I'm trying
> to build on Mac OS X Lion, but I will try it on Linux sometime today and see
> how that goes.  The default gcc is gcc 4.2.1 and I've tried gcc-4.7 as well,
> which gives less errors (-Weverything is unknown).
> 
> Maybe I can ask a few questions.
> 1. What operating system do you build it on?

Same as you.

> 1. What compiler and version do you build it with?

Clang 3.1 (from MacPorts).

> 1. What arguments to configure do you use?

bin/config.sh

> 1. What version of boost is required?

1.49

> 1. Are there any other system requirements such as libraries, etc.?

I'm compiling this code as c++11, so in the near future it will require
libc++ in order to provide the modern libraries to Clang.

John
